// Copyright 2026 Qoder (qoder.in). All rights reserved.
// Use of this source code is governed by a BSD-style license.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_REFRESH_RATE_API_G_H_
#define PIGEON_REFRESH_RATE_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace refresh_rate {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class RefreshRateHostApi;
  friend class RefreshRateFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class DisplayInfoMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  DisplayInfoMessage();

  // Constructs an object setting all fields.
  explicit DisplayInfoMessage(
    const double* current_rate,
    const double* max_rate,
    const double* min_rate,
    const flutter::EncodableList* supported_rates,
    const bool* is_variable_refresh_rate,
    const double* engine_target_rate,
    const bool* ios_pro_motion_enabled,
    const int64_t* android_api_level,
    const bool* is_low_power_mode,
    const int64_t* thermal_state_index,
    const bool* has_adaptive_refresh_rate,
    const std::string* display_server,
    const int64_t* monitor_count);

  const double* current_rate() const;
  void set_current_rate(const double* value_arg);
  void set_current_rate(double value_arg);

  const double* max_rate() const;
  void set_max_rate(const double* value_arg);
  void set_max_rate(double value_arg);

  const double* min_rate() const;
  void set_min_rate(const double* value_arg);
  void set_min_rate(double value_arg);

  const flutter::EncodableList* supported_rates() const;
  void set_supported_rates(const flutter::EncodableList* value_arg);
  void set_supported_rates(const flutter::EncodableList& value_arg);

  const bool* is_variable_refresh_rate() const;
  void set_is_variable_refresh_rate(const bool* value_arg);
  void set_is_variable_refresh_rate(bool value_arg);

  const double* engine_target_rate() const;
  void set_engine_target_rate(const double* value_arg);
  void set_engine_target_rate(double value_arg);

  const bool* ios_pro_motion_enabled() const;
  void set_ios_pro_motion_enabled(const bool* value_arg);
  void set_ios_pro_motion_enabled(bool value_arg);

  const int64_t* android_api_level() const;
  void set_android_api_level(const int64_t* value_arg);
  void set_android_api_level(int64_t value_arg);

  const bool* is_low_power_mode() const;
  void set_is_low_power_mode(const bool* value_arg);
  void set_is_low_power_mode(bool value_arg);

  const int64_t* thermal_state_index() const;
  void set_thermal_state_index(const int64_t* value_arg);
  void set_thermal_state_index(int64_t value_arg);

  const bool* has_adaptive_refresh_rate() const;
  void set_has_adaptive_refresh_rate(const bool* value_arg);
  void set_has_adaptive_refresh_rate(bool value_arg);

  const std::string* display_server() const;
  void set_display_server(const std::string_view* value_arg);
  void set_display_server(std::string_view value_arg);

  const int64_t* monitor_count() const;
  void set_monitor_count(const int64_t* value_arg);
  void set_monitor_count(int64_t value_arg);


 private:
  static DisplayInfoMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class RefreshRateHostApi;
  friend class RefreshRateFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<double> current_rate_;
  std::optional<double> max_rate_;
  std::optional<double> min_rate_;
  std::optional<flutter::EncodableList> supported_rates_;
  std::optional<bool> is_variable_refresh_rate_;
  std::optional<double> engine_target_rate_;
  std::optional<bool> ios_pro_motion_enabled_;
  std::optional<int64_t> android_api_level_;
  std::optional<bool> is_low_power_mode_;
  std::optional<int64_t> thermal_state_index_;
  std::optional<bool> has_adaptive_refresh_rate_;
  std::optional<std::string> display_server_;
  std::optional<int64_t> monitor_count_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class RefreshRateHostApi {
 public:
  RefreshRateHostApi(const RefreshRateHostApi&) = delete;
  RefreshRateHostApi& operator=(const RefreshRateHostApi&) = delete;
  virtual ~RefreshRateHostApi() {}
  virtual ErrorOr<DisplayInfoMessage> GetDisplayInfo() = 0;
  virtual std::optional<FlutterError> Enable() = 0;
  virtual std::optional<FlutterError> Disable() = 0;
  virtual std::optional<FlutterError> PreferMax() = 0;
  virtual std::optional<FlutterError> PreferDefault() = 0;
  virtual std::optional<FlutterError> MatchContent(double fps) = 0;
  virtual std::optional<FlutterError> Boost(int64_t duration_ms) = 0;
  virtual std::optional<FlutterError> SetCategory(int64_t category_index) = 0;
  virtual std::optional<FlutterError> SetTouchBoost(bool enabled) = 0;
  virtual ErrorOr<bool> IsSupported() = 0;

  // The codec used by RefreshRateHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `RefreshRateHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    RefreshRateHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    RefreshRateHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  RefreshRateHostApi() = default;

};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class RefreshRateFlutterApi {
 public:
  RefreshRateFlutterApi(flutter::BinaryMessenger* binary_messenger);
  RefreshRateFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnDisplayInfoChanged(
    const DisplayInfoMessage& info,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace refresh_rate
#endif  // PIGEON_REFRESH_RATE_API_G_H_
