// Copyright 2026 Qoder (qoder.in). All rights reserved.
// Use of this source code is governed by a BSD-style license.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "refresh_rate_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace refresh_rate {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// DisplayInfoMessage

DisplayInfoMessage::DisplayInfoMessage() {}

DisplayInfoMessage::DisplayInfoMessage(
  const double* current_rate,
  const double* max_rate,
  const double* min_rate,
  const EncodableList* supported_rates,
  const bool* is_variable_refresh_rate,
  const double* engine_target_rate,
  const bool* ios_pro_motion_enabled,
  const int64_t* android_api_level,
  const bool* is_low_power_mode,
  const int64_t* thermal_state_index,
  const bool* has_adaptive_refresh_rate,
  const std::string* display_server,
  const int64_t* monitor_count)
 : current_rate_(current_rate ? std::optional<double>(*current_rate) : std::nullopt),
    max_rate_(max_rate ? std::optional<double>(*max_rate) : std::nullopt),
    min_rate_(min_rate ? std::optional<double>(*min_rate) : std::nullopt),
    supported_rates_(supported_rates ? std::optional<EncodableList>(*supported_rates) : std::nullopt),
    is_variable_refresh_rate_(is_variable_refresh_rate ? std::optional<bool>(*is_variable_refresh_rate) : std::nullopt),
    engine_target_rate_(engine_target_rate ? std::optional<double>(*engine_target_rate) : std::nullopt),
    ios_pro_motion_enabled_(ios_pro_motion_enabled ? std::optional<bool>(*ios_pro_motion_enabled) : std::nullopt),
    android_api_level_(android_api_level ? std::optional<int64_t>(*android_api_level) : std::nullopt),
    is_low_power_mode_(is_low_power_mode ? std::optional<bool>(*is_low_power_mode) : std::nullopt),
    thermal_state_index_(thermal_state_index ? std::optional<int64_t>(*thermal_state_index) : std::nullopt),
    has_adaptive_refresh_rate_(has_adaptive_refresh_rate ? std::optional<bool>(*has_adaptive_refresh_rate) : std::nullopt),
    display_server_(display_server ? std::optional<std::string>(*display_server) : std::nullopt),
    monitor_count_(monitor_count ? std::optional<int64_t>(*monitor_count) : std::nullopt) {}

const double* DisplayInfoMessage::current_rate() const {
  return current_rate_ ? &(*current_rate_) : nullptr;
}

void DisplayInfoMessage::set_current_rate(const double* value_arg) {
  current_rate_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_current_rate(double value_arg) {
  current_rate_ = value_arg;
}


const double* DisplayInfoMessage::max_rate() const {
  return max_rate_ ? &(*max_rate_) : nullptr;
}

void DisplayInfoMessage::set_max_rate(const double* value_arg) {
  max_rate_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_max_rate(double value_arg) {
  max_rate_ = value_arg;
}


const double* DisplayInfoMessage::min_rate() const {
  return min_rate_ ? &(*min_rate_) : nullptr;
}

void DisplayInfoMessage::set_min_rate(const double* value_arg) {
  min_rate_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_min_rate(double value_arg) {
  min_rate_ = value_arg;
}


const EncodableList* DisplayInfoMessage::supported_rates() const {
  return supported_rates_ ? &(*supported_rates_) : nullptr;
}

void DisplayInfoMessage::set_supported_rates(const EncodableList* value_arg) {
  supported_rates_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_supported_rates(const EncodableList& value_arg) {
  supported_rates_ = value_arg;
}


const bool* DisplayInfoMessage::is_variable_refresh_rate() const {
  return is_variable_refresh_rate_ ? &(*is_variable_refresh_rate_) : nullptr;
}

void DisplayInfoMessage::set_is_variable_refresh_rate(const bool* value_arg) {
  is_variable_refresh_rate_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_is_variable_refresh_rate(bool value_arg) {
  is_variable_refresh_rate_ = value_arg;
}


const double* DisplayInfoMessage::engine_target_rate() const {
  return engine_target_rate_ ? &(*engine_target_rate_) : nullptr;
}

void DisplayInfoMessage::set_engine_target_rate(const double* value_arg) {
  engine_target_rate_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_engine_target_rate(double value_arg) {
  engine_target_rate_ = value_arg;
}


const bool* DisplayInfoMessage::ios_pro_motion_enabled() const {
  return ios_pro_motion_enabled_ ? &(*ios_pro_motion_enabled_) : nullptr;
}

void DisplayInfoMessage::set_ios_pro_motion_enabled(const bool* value_arg) {
  ios_pro_motion_enabled_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_ios_pro_motion_enabled(bool value_arg) {
  ios_pro_motion_enabled_ = value_arg;
}


const int64_t* DisplayInfoMessage::android_api_level() const {
  return android_api_level_ ? &(*android_api_level_) : nullptr;
}

void DisplayInfoMessage::set_android_api_level(const int64_t* value_arg) {
  android_api_level_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_android_api_level(int64_t value_arg) {
  android_api_level_ = value_arg;
}


const bool* DisplayInfoMessage::is_low_power_mode() const {
  return is_low_power_mode_ ? &(*is_low_power_mode_) : nullptr;
}

void DisplayInfoMessage::set_is_low_power_mode(const bool* value_arg) {
  is_low_power_mode_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_is_low_power_mode(bool value_arg) {
  is_low_power_mode_ = value_arg;
}


const int64_t* DisplayInfoMessage::thermal_state_index() const {
  return thermal_state_index_ ? &(*thermal_state_index_) : nullptr;
}

void DisplayInfoMessage::set_thermal_state_index(const int64_t* value_arg) {
  thermal_state_index_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_thermal_state_index(int64_t value_arg) {
  thermal_state_index_ = value_arg;
}


const bool* DisplayInfoMessage::has_adaptive_refresh_rate() const {
  return has_adaptive_refresh_rate_ ? &(*has_adaptive_refresh_rate_) : nullptr;
}

void DisplayInfoMessage::set_has_adaptive_refresh_rate(const bool* value_arg) {
  has_adaptive_refresh_rate_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_has_adaptive_refresh_rate(bool value_arg) {
  has_adaptive_refresh_rate_ = value_arg;
}


const std::string* DisplayInfoMessage::display_server() const {
  return display_server_ ? &(*display_server_) : nullptr;
}

void DisplayInfoMessage::set_display_server(const std::string_view* value_arg) {
  display_server_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_display_server(std::string_view value_arg) {
  display_server_ = value_arg;
}


const int64_t* DisplayInfoMessage::monitor_count() const {
  return monitor_count_ ? &(*monitor_count_) : nullptr;
}

void DisplayInfoMessage::set_monitor_count(const int64_t* value_arg) {
  monitor_count_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void DisplayInfoMessage::set_monitor_count(int64_t value_arg) {
  monitor_count_ = value_arg;
}


EncodableList DisplayInfoMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(13);
  list.push_back(current_rate_ ? EncodableValue(*current_rate_) : EncodableValue());
  list.push_back(max_rate_ ? EncodableValue(*max_rate_) : EncodableValue());
  list.push_back(min_rate_ ? EncodableValue(*min_rate_) : EncodableValue());
  list.push_back(supported_rates_ ? EncodableValue(*supported_rates_) : EncodableValue());
  list.push_back(is_variable_refresh_rate_ ? EncodableValue(*is_variable_refresh_rate_) : EncodableValue());
  list.push_back(engine_target_rate_ ? EncodableValue(*engine_target_rate_) : EncodableValue());
  list.push_back(ios_pro_motion_enabled_ ? EncodableValue(*ios_pro_motion_enabled_) : EncodableValue());
  list.push_back(android_api_level_ ? EncodableValue(*android_api_level_) : EncodableValue());
  list.push_back(is_low_power_mode_ ? EncodableValue(*is_low_power_mode_) : EncodableValue());
  list.push_back(thermal_state_index_ ? EncodableValue(*thermal_state_index_) : EncodableValue());
  list.push_back(has_adaptive_refresh_rate_ ? EncodableValue(*has_adaptive_refresh_rate_) : EncodableValue());
  list.push_back(display_server_ ? EncodableValue(*display_server_) : EncodableValue());
  list.push_back(monitor_count_ ? EncodableValue(*monitor_count_) : EncodableValue());
  return list;
}

DisplayInfoMessage DisplayInfoMessage::FromEncodableList(const EncodableList& list) {
  DisplayInfoMessage decoded;
  auto& encodable_current_rate = list[0];
  if (!encodable_current_rate.IsNull()) {
    decoded.set_current_rate(std::get<double>(encodable_current_rate));
  }
  auto& encodable_max_rate = list[1];
  if (!encodable_max_rate.IsNull()) {
    decoded.set_max_rate(std::get<double>(encodable_max_rate));
  }
  auto& encodable_min_rate = list[2];
  if (!encodable_min_rate.IsNull()) {
    decoded.set_min_rate(std::get<double>(encodable_min_rate));
  }
  auto& encodable_supported_rates = list[3];
  if (!encodable_supported_rates.IsNull()) {
    decoded.set_supported_rates(std::get<EncodableList>(encodable_supported_rates));
  }
  auto& encodable_is_variable_refresh_rate = list[4];
  if (!encodable_is_variable_refresh_rate.IsNull()) {
    decoded.set_is_variable_refresh_rate(std::get<bool>(encodable_is_variable_refresh_rate));
  }
  auto& encodable_engine_target_rate = list[5];
  if (!encodable_engine_target_rate.IsNull()) {
    decoded.set_engine_target_rate(std::get<double>(encodable_engine_target_rate));
  }
  auto& encodable_ios_pro_motion_enabled = list[6];
  if (!encodable_ios_pro_motion_enabled.IsNull()) {
    decoded.set_ios_pro_motion_enabled(std::get<bool>(encodable_ios_pro_motion_enabled));
  }
  auto& encodable_android_api_level = list[7];
  if (!encodable_android_api_level.IsNull()) {
    decoded.set_android_api_level(std::get<int64_t>(encodable_android_api_level));
  }
  auto& encodable_is_low_power_mode = list[8];
  if (!encodable_is_low_power_mode.IsNull()) {
    decoded.set_is_low_power_mode(std::get<bool>(encodable_is_low_power_mode));
  }
  auto& encodable_thermal_state_index = list[9];
  if (!encodable_thermal_state_index.IsNull()) {
    decoded.set_thermal_state_index(std::get<int64_t>(encodable_thermal_state_index));
  }
  auto& encodable_has_adaptive_refresh_rate = list[10];
  if (!encodable_has_adaptive_refresh_rate.IsNull()) {
    decoded.set_has_adaptive_refresh_rate(std::get<bool>(encodable_has_adaptive_refresh_rate));
  }
  auto& encodable_display_server = list[11];
  if (!encodable_display_server.IsNull()) {
    decoded.set_display_server(std::get<std::string>(encodable_display_server));
  }
  auto& encodable_monitor_count = list[12];
  if (!encodable_monitor_count.IsNull()) {
    decoded.set_monitor_count(std::get<int64_t>(encodable_monitor_count));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        return CustomEncodableValue(DisplayInfoMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(DisplayInfoMessage)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<DisplayInfoMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by RefreshRateHostApi.
const flutter::StandardMessageCodec& RefreshRateHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `RefreshRateHostApi` to handle messages through the `binary_messenger`.
void RefreshRateHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  RefreshRateHostApi* api) {
  RefreshRateHostApi::SetUp(binary_messenger, api, "");
}

void RefreshRateHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  RefreshRateHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.getDisplayInfo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<DisplayInfoMessage> output = api->GetDisplayInfo();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.enable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Enable();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.disable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Disable();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.preferMax" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->PreferMax();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.preferDefault" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->PreferDefault();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.matchContent" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_fps_arg = args.at(0);
          if (encodable_fps_arg.IsNull()) {
            reply(WrapError("fps_arg unexpectedly null."));
            return;
          }
          const auto& fps_arg = std::get<double>(encodable_fps_arg);
          std::optional<FlutterError> output = api->MatchContent(fps_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.boost" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_duration_ms_arg = args.at(0);
          if (encodable_duration_ms_arg.IsNull()) {
            reply(WrapError("duration_ms_arg unexpectedly null."));
            return;
          }
          const int64_t duration_ms_arg = encodable_duration_ms_arg.LongValue();
          std::optional<FlutterError> output = api->Boost(duration_ms_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.setCategory" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_category_index_arg = args.at(0);
          if (encodable_category_index_arg.IsNull()) {
            reply(WrapError("category_index_arg unexpectedly null."));
            return;
          }
          const int64_t category_index_arg = encodable_category_index_arg.LongValue();
          std::optional<FlutterError> output = api->SetCategory(category_index_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.setTouchBoost" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_enabled_arg = args.at(0);
          if (encodable_enabled_arg.IsNull()) {
            reply(WrapError("enabled_arg unexpectedly null."));
            return;
          }
          const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
          std::optional<FlutterError> output = api->SetTouchBoost(enabled_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.refresh_rate.RefreshRateHostApi.isSupported" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->IsSupported();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue RefreshRateHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue RefreshRateHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
RefreshRateFlutterApi::RefreshRateFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

RefreshRateFlutterApi::RefreshRateFlutterApi(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& RefreshRateFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void RefreshRateFlutterApi::OnDisplayInfoChanged(
  const DisplayInfoMessage& info_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.refresh_rate.RefreshRateFlutterApi.onDisplayInfoChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(info_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace refresh_rate
